### ISSUE TITLE
exit -> Login -> Login loop issue

### ISSUE THREAD

**Issue by raghukamma** [raghukamma/SFTP-Client#28]
Login to a server, do something whatever you want to or just use "exit" command.
Don't kill the terminal. In the same terminal, 3 options are visible (connect, save, exit). But, if we login using host name, user name and password, we end up at login menu again i.e., we can not login and end up in the same loop again and agin. 
we need to implement the logout feature properly so it actually exits completely

**Comment by saitejapdx** [comment]
Raised PR to handle this bug: https://github.com/raghukamma/SFTP-Client/pull/30

**Comment by saitejapdx** [comment]
PR merged
